/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import javax.swing.DefaultListModel;
import java.util.List;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/**
 *
 * @author LENOVO
 */
public class JFrameUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

        private final MysqlMahasiswaService service;
        private DefaultListModel<String> dlmId;
        private DefaultListModel<String> dlmNama;
    
    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        
        // Instansiasi objek service database
        this.service = new MysqlMahasiswaService();
        
        // Siapkan model untuk masing-masing jList
        this.dlmId = new DefaultListModel<>();
        this.dlmNama = new DefaultListModel<>();
        
        jListId.setModel(dlmId);
        jListNama.setModel(dlmNama);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabelDataID = new javax.swing.JLabel();
        jLabelDataNama = new javax.swing.JLabel();
        jLabelJudulKelolaMhs = new javax.swing.JLabel();
        jButtonAmbilSemuaData = new javax.swing.JButton();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldEditId = new javax.swing.JTextField();
        jTextFieldEditNama = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldHapusId = new javax.swing.JTextField();
        jTextFieldHapusNama = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetIndeks = new javax.swing.JButton();
        jButtonTambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListId = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelJudulKelolaMhs1 = new javax.swing.JLabel();
        jLabelJudulKelolaMhs2 = new javax.swing.JLabel();
        jLabelStatusReset = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelDataID.setText("ID");

        jLabelDataNama.setText("NAMA");

        jLabelJudulKelolaMhs.setText("KELOLA DATA MAHASISWA");

        jButtonAmbilSemuaData.setText("Ambil Semua Data");
        jButtonAmbilSemuaData.addActionListener(this::jButtonAmbilSemuaDataActionPerformed);

        jLabelNama.setText("Nama");

        jTextFieldEditId.addActionListener(this::jTextFieldEditIdActionPerformed);

        jTextFieldEditNama.addActionListener(this::jTextFieldEditNamaActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonResetIndeks.setText("Reset indeks");
        jButtonResetIndeks.addActionListener(this::jButtonResetIndeksActionPerformed);

        jButtonTambah.setText("Tambahkan");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        jListId.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListId);

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabelStatusReset.setText("Index di reset ke 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataID)
                        .addGap(54, 54, 54)
                        .addComponent(jLabelDataNama))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNama)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldHapusId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jTextFieldEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEditNama)
                            .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJudulKelolaMhs)
                            .addComponent(jButtonAmbilSemuaData, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNama)
                            .addComponent(jButtonTambah)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonResetIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelJudulKelolaMhs1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelStatusReset)))
                        .addGap(0, 38, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(359, Short.MAX_VALUE)
                    .addComponent(jLabelJudulKelolaMhs2)
                    .addGap(145, 145, 145)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataID)
                    .addComponent(jLabelDataNama)
                    .addComponent(jLabelJudulKelolaMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAmbilSemuaData)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTambah)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEditId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHapusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndeks)
                            .addComponent(jLabelJudulKelolaMhs1)
                            .addComponent(jLabelStatusReset)))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(273, Short.MAX_VALUE)
                    .addComponent(jLabelJudulKelolaMhs2)
                    .addGap(27, 27, 27)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        String nama = jTextFieldNama.getText().trim();
        if (!nama.isEmpty()) {
            // Membuat objek Mahasiswa melalui service pembantu
            Mahasiswa mhs = service.makeMhsObject();
            mhs.setNama(nama);
            
            // Simpan ke database
            service.add(mhs);
            
            // Bersihkan field dan refresh list UI
            jTextFieldNama.setText("");
            loadDataToHonest();
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jTextFieldEditIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditIdActionPerformed

    private void jTextFieldEditNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditNamaActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        String idStr = jTextFieldEditId.getText().trim();
        String namaBaru = jTextFieldEditNama.getText().trim();
        
        if (!idStr.isEmpty() && !namaBaru.isEmpty()) {
            int id = Integer.parseInt(idStr);
            
            // Ambil data Mahasiswa yang sudah ada berdasarkan ID
            Mahasiswa mhs = service.getById(id);
            if (mhs != null) {
                mhs.setNama(namaBaru);
                
                // Eksekusi update ke database
                service.update(mhs);
                
                // Bersihkan field dan refresh list UI
                jTextFieldEditId.setText("");
                jTextFieldEditNama.setText("");
                loadDataToHonest();
            }
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilSemuaDataActionPerformed
        // Ambil data terbaru dari database dan perbarui UI
        loadDataToHonest();
    }//GEN-LAST:event_jButtonAmbilSemuaDataActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        String idStr = jTextFieldHapusId.getText().trim();
        
        if (!idStr.isEmpty()) {
            int id = Integer.parseInt(idStr);
            
            // Eksekusi delete berdasarkan id
            service.delete(id);
            
            // Bersihkan field dan refresh list UI
            jTextFieldHapusId.setText("");
            jTextFieldHapusNama.setText("");
            loadDataToHonest();
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetIndeksActionPerformed
        // Eksekusi reset indeks tabel mahasiswa ke 1
        service.indexReset();
        jLabelStatusReset.setText("Index di reset ke 0");
        // Refresh UI untuk melihat perubahannya
        loadDataToHonest();
    }//GEN-LAST:event_jButtonResetIndeksActionPerformed

        // Helper method untuk me-refresh/mengambil data terbaru dari DB ke GUI
    private void loadDataToHonest() {
        dlmId.clear();
        dlmNama.clear();
        
        List<Mahasiswa> listMhs = service.getAll();
        for (Mahasiswa mhs : listMhs) {
            dlmId.addElement(String.valueOf(mhs.getId()));
            dlmNama.addElement(mhs.getNama());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbilSemuaData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonResetIndeks;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelDataID;
    private javax.swing.JLabel jLabelDataNama;
    private javax.swing.JLabel jLabelJudulKelolaMhs;
    private javax.swing.JLabel jLabelJudulKelolaMhs1;
    private javax.swing.JLabel jLabelJudulKelolaMhs2;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelStatusReset;
    private javax.swing.JList<String> jListId;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldEditId;
    private javax.swing.JTextField jTextFieldEditNama;
    private javax.swing.JTextField jTextFieldHapusId;
    private javax.swing.JTextField jTextFieldHapusNama;
    private javax.swing.JTextField jTextFieldNama;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
